#!/bin/sh
# paritydata.sh: data/holes.txt as a golf test file, for the parity test
# (golf's own tests cannot read files). holedata.sh runs it; run it alone
# after editing data/holes.txt by hand.
set -eu
root=$(cd "$(dirname "$0")/.." && pwd)
out=$root/gno.land/r/gnogolf/golf/parity_data_test.gno
{
	echo "// Code generated by scripts/paritydata.sh from data/holes.txt. DO NOT EDIT."
	echo
	echo "package golf"
	echo
	echo "// courseData is data/holes.txt: slot, the realm the hole is today, the"
	echo "// first 4 bytes of the data's sha256, and the data in hex."
	echo "var courseData = [][4]string{"
	awk '{printf "\t{\"%s\", \"%s\", \"%s\", \"%s\"},\n", $1, $2, $3, $4}' "$root/data/holes.txt"
	echo "}"
} >"$out"
echo "$out: $(grep -c '^	{' "$out") holes"
