#!/bin/sh
# paritydata.sh: data/holes.txt as a golf test file, for the parity test
# (golf's own tests cannot read files), into v1 and v2 alike. holedata.sh
# runs it; run it alone after editing data/holes.txt by hand. OUT writes it
# once, elsewhere (holedata.sh --check compares it with the committed files).
set -eu
root=$(cd "$(dirname "$0")/.." && pwd)
gen() {
{
	echo "// Code generated by scripts/paritydata.sh from data/holes.txt. DO NOT EDIT."
	echo
	echo "package golf"
	echo
	echo "// courseData is data/holes.txt: slot, the realm the hole is today, the"
	echo "// first 4 bytes of the data's sha256, and the data in hex."
	echo "var courseData = [][4]string{"
	awk '{printf "\t{\"%s\", \"%s\", \"%s\", \"%s\"},\n", $1, $2, $3, $4}' "$root/data/holes.txt"
	echo "}"
} >"$1"
echo "$1: $(grep -c '^	{' "$1") holes"
}
if [ -n "${OUT:-}" ]; then
	gen "$OUT"
else
	for g in golf golf/v2; do gen "$root/gno.land/r/gnogolf/$g/parity_data_test.gno"; done
fi
