#!/bin/sh
# publishdata.sh [per]: data/holes.txt as MsgRun scripts that Publish every
# course hole into its slot, per holes a script (default 7: the heaviest
# seven publish in 0.86e9 gas, which keeps each script under 1e9), written to
# scripts/publish/. Run each one as the course's owner (a MsgRun, e.g.
# `gnokey maketx run`), in order; a slot whose data is already its current
# version is skipped, so a script can be run again after a failure.
#
# REALM is the golf realm to publish to (default gno.land/r/gnogolf/golf),
# OUT where the scripts go (default scripts/publish; it is emptied first), so
# a namespaced set does not overwrite the committed one:
#
#   REALM=gno.land/r/nym-golfer000/golf OUT=/tmp/pub scripts/publishdata.sh
# scripts/publish/verify.gno then checks every slot (run it simulated).
set -eu
root=$(cd "$(dirname "$0")/.." && pwd)
per=${1:-7}
realm=${REALM:-gno.land/r/gnogolf/golf}
out=${OUT:-$root/scripts/publish}
rm -rf "$out"
mkdir -p "$out"
awk -v per="$per" -v realm="$realm" -v out="$out" '
function head(f, k) {
	print "// Publishes course holes " k " of data/holes.txt, generated by" > f
	print "// scripts/publishdata.sh. Run it as the course'"'"'s owner." > f
	print "package main\n" > f
	print "import \"" realm "\"\n" > f
	print "func main(cur realm) {" > f
	print "\tfor _, h := range [][2]string{" > f
}
function tail(f) {
	print "\t} {" > f
	print "\t\t// the data already current there: nothing to do" > f
	print "\t\tif id := golf.Current(h[0]); id != \"\" && golf.HoleData(id) == h[1] {" > f
	print "\t\t\tcontinue" > f
	print "\t\t}" > f
	print "\t\tprintln(golf.Publish(cross(cur), h[0], h[1], \"\"))" > f
	print "\t}" > f
	print "}" > f
	close(f)
}
{
	if ((NR - 1) % per == 0) {
		if (f != "") tail(f)
		f = sprintf("%s/publish-%02d.gno", out, (NR - 1) / per + 1)
		head(f, NR "-" (NR + per - 1))
	}
	printf "\t\t{\"%s\", \"%s\"},\n", $1, $4 > f
}
END { if (f != "") tail(f) }
' "$root/data/holes.txt"
# and a read-only check to run after them (run it simulated): the current
# version of every slot holds the data it is listed with
{
	cat <<EOF
// Checks every slot of data/holes.txt against the chain: its current
// version's data has the sha it is listed with. Generated by
// scripts/publishdata.sh; run it simulated.
package main

import (
	"strings"

	"$realm"
)

func main() {
	ok, bad := 0, ""
	for _, h := range [][2]string{
EOF
	awk '{printf "\t\t{\"%s\", \"%s\"},\n", $1, $3}' "$root/data/holes.txt"
	cat <<'EOF'
	} {
		// the current version's entry in Versions, up to its end
		if id := golf.Current(h[0]); id != "" {
			v := golf.Versions(h[0])
			v = v[strings.Index(v, `"id":"`+id+`"`):]
			if strings.Contains(v[:strings.Index(v, "}")], `"sha":"`+h[1]) {
				ok++
				continue
			}
		}
		bad += " " + h[0]
	}
	println(ok, "slots hold their data; missing or other:", bad)
}
EOF
} >"$out/verify.gno"
ls -la "$out" | awk 'NR > 1 {print $5, $9}'
